language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  fqdn: explorata.io
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
